export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  SCAN: "/scan",
  RESULT: "/result/:code",
  PRODUCT: "/product/:id",
  VERIFY: "/verify/:code",
  ANALYTICS: "/analytics",
  HISTORY: "/history",
  PROFILE: "/profile",
  REPORTS: "/reports",
  NOTIFICATIONS: "/notifications",
} as const;
