export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  SCAN: "/scan",
  RESULT: "/result/:code",
  PRODUCT: "/product/:id",
  PRODUCT_LIST: "/products",
  QR_CODE: "/qr-code",
  ADD_PRODUCT: "/add-product",
  VERIFY: "/verify/:code",
  VERIFY_EMAIL: "/verify-email",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_ORGANIZATIONS: "/admin/organizations",
  ADMIN_APPLICATIONS: "/admin/applications",
  ADMIN_CONSUMER_REPORTS: "/admin/consumer-reports",
  ADMIN_PROMOTION_TIPS: "/admin/promotion-tips",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
  ANALYTICS: "/analytics",
  HISTORY: "/history",
  PROFILE: "/profile",
  REPORTS: "/reports",
  NOTIFICATIONS: "/notifications",
  SETTINGS: "/settings",
} as const;