export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  MANUFACTURER_LOGIN: "/manufacturer/login",
  MANUFACTURER_SIGNUP: "/manufacturer/signup",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  SCAN: "/scan",
  RESULT: "/result/:code",
  PRODUCT: "/product/:id",
  VERIFY: "/verify/:code",
  ANALYTICS: "/analytics",
  HISTORY: "/history",
  PROFILE: "/profile",
  REPORTS: "/reports",
  NOTIFICATIONS: "/notifications",
  FORGOT_PASSWORD: "/forgot-password",
  CHECK_YOUR_EMAIL: "/check-your-email",
  PRODUCT_UPLOAD: "/manufacturer/products/upload",
} as const;
